# Generated by Django 5.0.7 on 2024-11-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0002_slider_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='Slider_desc',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='Slider_head',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='Slider_image',
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_desc',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/'),
        ),
    ]
