# Generated by Django 5.0.7 on 2024-11-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0003_remove_slider_slider_desc_remove_slider_slider_head_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_desc', models.TextField()),
            ],
        ),
    ]
