# Generated by Django 5.0.7 on 2024-11-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_image', models.ImageField(upload_to='Details/')),
                ('detail_desc', models.TextField()),
            ],
        ),
    ]
