# Generated by Django 5.0.7 on 2024-11-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0005_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=100)),
                ('review_head', models.CharField(max_length=100)),
                ('review_image', models.ImageField(upload_to='Reviews/')),
                ('review_desc', models.TextField()),
            ],
        ),
    ]
