# Generated by Django 5.0.7 on 2024-11-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0006_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='review_desc',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='review_image',
        ),
    ]
