# Generated by Django 5.0.7 on 2024-11-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0007_remove_reviews_review_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='detail_title',
            field=models.CharField(default='mulching', max_length=100),
        ),
    ]
