# Generated by Django 5.0.7 on 2024-11-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0010_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_title', models.CharField(max_length=100)),
                ('demo_desc', models.TextField()),
            ],
        ),
    ]
