# Generated by Django 5.0.7 on 2024-11-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0011_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('post_desc', models.TextField()),
                ('post_date', models.DateTimeField()),
            ],
        ),
    ]
