# Generated by Django 5.0.7 on 2024-11-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0013_remove_post_post_date_post_post_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_title', models.CharField(max_length=100)),
                ('desk_head', models.CharField(max_length=100)),
                ('desk_image', models.ImageField(blank=True, null=True, upload_to='desks/')),
                ('desk_desc', models.TextField()),
            ],
        ),
    ]
