# Generated by Django 5.0.7 on 2024-11-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0014_desk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desk',
            old_name='desk_title',
            new_name='desk_title1',
        ),
        migrations.AddField(
            model_name='desk',
            name='desk_title2',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
