# Generated by Django 5.0.7 on 2024-11-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0016_remove_desk_desk_desc_desk_desk_desc1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_title', models.CharField(max_length=100)),
                ('pest_head', models.CharField(max_length=100)),
            ],
        ),
    ]
