# Generated by Django 5.0.7 on 2024-11-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0017_pest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.DeleteModel(
            name='Desk',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='Pest',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
