# Generated by Django 5.0.7 on 2024-11-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0018_delete_case_delete_demo_delete_desk_delete_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_title', models.CharField(max_length=100)),
                ('detail_desc', models.TextField()),
                ('detail_num', models.IntegerField()),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='details/')),
            ],
        ),
    ]
