# Generated by Django 5.0.7 on 2024-11-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0019_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_title', models.CharField(max_length=100)),
                ('recent_desc', models.TextField()),
            ],
        ),
    ]
