# Generated by Django 5.0.7 on 2024-11-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0022_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=100)),
                ('test_desc', models.TextField()),
                ('test_image', models.ImageField(blank=True, null=True, upload_to='tests/')),
            ],
        ),
    ]
