# Generated by Django 5.0.7 on 2024-11-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0023_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_num',
        ),
    ]
