# Generated by Django 5.0.7 on 2024-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0024_remove_post_post_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Json',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_image', models.FileField(blank=True, null=True, upload_to='jsons/')),
            ],
        ),
    ]
