# Generated by Django 5.0.7 on 2024-11-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0025_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='json',
            name='json_image',
        ),
        migrations.AddField(
            model_name='json',
            name='json_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='json',
            name='json_title',
            field=models.CharField(default='YourDefaultValue', max_length=100),
        ),
    ]
