# Generated by Django 5.0.7 on 2024-12-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0029_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
