# Generated by Django 5.1.3 on 2024-12-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0031_new"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_title", models.CharField(max_length=100)),
                ("section_desc", models.TextField()),
            ],
        ),
    ]
