# Generated by Django 5.1.3 on 2024-12-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0032_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="section_image",
            field=models.ImageField(blank=True, null=True, upload_to="sections/"),
        ),
    ]
