# Generated by Django 5.1.3 on 2024-12-02 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0033_section_section_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="section_image",
        ),
    ]
