# Generated by Django 5.1.3 on 2024-12-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0035_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_img",
            field=models.ImageField(default="none", upload_to="images/"),
        ),
    ]
