# Generated by Django 5.1.3 on 2024-12-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0036_alter_image_image_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Excel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("excel_title", models.CharField(max_length=100)),
                ("excel_desc", models.TextField()),
                ("excel_button", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.AlterField(
            model_name="about",
            name="about_image",
            field=models.ImageField(default="default_image.jpg", upload_to="about/"),
        ),
        migrations.AlterField(
            model_name="details",
            name="detail_image",
            field=models.ImageField(default="default_image.jpg", upload_to="details/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(default="default_image.jpg", upload_to="posts/"),
        ),
        migrations.AlterField(
            model_name="test",
            name="test_image",
            field=models.ImageField(default="default_image.jpg", upload_to="tests/"),
        ),
        migrations.AlterField(
            model_name="test",
            name="test_title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
