# Generated by Django 5.1.3 on 2024-12-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0038_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(max_length=100)),
                ("event_head", models.CharField(max_length=100)),
                (
                    "event_image",
                    models.ImageField(default="default_image.jpg", upload_to="events/"),
                ),
            ],
        ),
    ]
