# Generated by Django 5.1.3 on 2024-12-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0040_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount_title", models.CharField(max_length=100)),
                ("discount_desc", models.TextField()),
                ("discount_number", models.IntegerField()),
                (
                    "discount_image",
                    models.ImageField(
                        default="default_image.jpg", upload_to="discounts/"
                    ),
                ),
            ],
        ),
    ]
