# Generated by Django 5.0.7 on 2024-12-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0041_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_title', models.CharField(max_length=100)),
                ('author_desc', models.TextField()),
            ],
        ),
    ]
