# Generated by Django 5.0.7 on 2024-12-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0046_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_title', models.CharField(max_length=100)),
                ('pixel_desc', models.TextField()),
                ('pixel_image', models.ImageField(default='default_image.jpg', upload_to='pixels/')),
            ],
        ),
    ]
