# Generated by Django 5.0.7 on 2024-12-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0047_pixel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Php',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('php_image', models.ImageField(default='default_image.jpg', upload_to='php/')),
            ],
        ),
    ]
