# Generated by Django 5.0.7 on 2024-12-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0048_php'),
    ]

    operations = [
        migrations.AddField(
            model_name='php',
            name='php_desc',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='php',
            name='php_head',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='php',
            name='php_title',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
