# Generated by Django 5.1.3 on 2024-12-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0049_php_php_desc_php_php_head_php_php_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="List_desc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_desc", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="list",
            name="list_desc",
        ),
        migrations.RemoveField(
            model_name="php",
            name="php_head",
        ),
        migrations.RemoveField(
            model_name="php",
            name="php_image",
        ),
    ]
