# Generated by Django 5.0.7 on 2024-12-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0050_list_desc_remove_list_list_desc_remove_php_php_head_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="section_image",
            field=models.ImageField(default="default_image.jpg", upload_to="sections/"),
        ),
    ]
