# Generated by Django 5.0.7 on 2024-12-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0051_section_section_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenda_img",
                    models.ImageField(default="default_image.jpg", upload_to="tendas/"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="section",
            name="section_image",
        ),
    ]
