# Generated by Django 5.0.7 on 2024-12-03 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0052_tenda_remove_section_section_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tenda",
        ),
    ]
