# Generated by Django 5.0.7 on 2024-12-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0053_delete_tenda"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_title", models.CharField(max_length=100)),
                ("comment_desc", models.TextField()),
                (
                    "comment_image",
                    models.ImageField(
                        default="default_image.jpg", upload_to="comments/"
                    ),
                ),
                ("comment_head", models.CharField(max_length=100)),
            ],
        ),
    ]
