# Generated by Django 5.0.7 on 2024-12-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0054_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pip_title', models.CharField(max_length=100)),
            ],
        ),
    ]
