# Generated by Django 5.0.7 on 2024-12-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0055_pip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pip',
        ),
    ]
