# Generated by Django 5.0.7 on 2024-12-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0056_delete_pip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_title', models.CharField(max_length=100)),
                ('shop_desc', models.TextField()),
            ],
        ),
    ]
