# Generated by Django 5.0.7 on 2024-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0058_remove_shop_shop_desc_shop_shop_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_title', models.CharField(max_length=100)),
                ('employee_desc', models.TextField()),
                ('employee_image', models.ImageField(default='default_image.jpg', upload_to='employees/')),
            ],
        ),
    ]
