# Generated by Django 5.0.7 on 2024-12-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0065_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conduct_title", models.CharField(default="nun", max_length=100)),
                ("conduct_head", models.CharField(default="nun", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Havel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("havel_title", models.CharField(default="none", max_length=100)),
                ("havel_desc", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
    ]
