# Generated by Django 5.0.7 on 2024-12-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0066_conduct_havel_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conduct',
        ),
        migrations.DeleteModel(
            name='Havel',
        ),
    ]
