# Generated by Django 5.0.7 on 2024-12-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0067_delete_conduct_delete_havel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=100)),
                ("contact_phone", models.IntegerField(max_length=100)),
                ("contact_message", models.TextField()),
            ],
        ),
    ]
