# Generated by Django 5.0.7 on 2024-12-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0068_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_title", models.CharField(max_length=100)),
                ("tax_head", models.CharField(max_length=100)),
            ],
        ),
    ]
