# Generated by Django 5.0.7 on 2024-12-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0070_delete_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_phone',
            field=models.IntegerField(),
        ),
    ]
