# Generated by Django 5.0.7 on 2024-12-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0071_alter_contact_contact_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours_title", models.CharField(max_length=100)),
                ("hours_list", models.TextField()),
            ],
        ),
    ]
