# Generated by Django 5.0.7 on 2024-12-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0073_our_remove_hours_hours_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='redeem_date',
            field=models.IntegerField(default='30'),
        ),
        migrations.AddField(
            model_name='pixel',
            name='redeem_month',
            field=models.DateField(default='Jan'),
        ),
    ]
