# Generated by Django 5.0.7 on 2024-12-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0075_alter_pixel_redeem_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pixel',
            old_name='redeem_date',
            new_name='date',
        ),
    ]
