# Generated by Django 5.0.7 on 2024-12-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0076_rename_redeem_date_pixel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pixel',
            old_name='redeem_month',
            new_name='month',
        ),
    ]
