# Generated by Django 5.0.7 on 2024-12-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo', '0077_rename_redeem_month_pixel_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pixel',
            name='date',
        ),
    ]
