# Generated by Django 5.0.7 on 2024-12-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0078_remove_pixel_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="pixel",
            name="date",
            field=models.IntegerField(default="2024-07-08"),
        ),
        migrations.AlterField(
            model_name="pixel",
            name="month",
            field=models.DateField(default="2024-12-08"),
        ),
    ]
