# Generated by Django 5.0.7 on 2024-12-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0079_pixel_date_alter_pixel_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pixel",
            name="date",
            field=models.DateField(default="2024-07-08"),
        ),
    ]
