# Generated by Django 5.0.7 on 2024-12-08 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kilimo", "0080_alter_pixel_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pixel",
            name="date",
        ),
    ]
